Repository google/wasefire, pull requests merged in 2023-10, with the labels that each got.

#233 Clean up prelude allocator
  crates/prelude/CHANGELOG.md
  crates/prelude/src/allocator.rs
Labels: for:security, for:maintainability

#234 Support nested tables for dependencies in ci-changelog script
  scripts/ci-changelog.sh
Labels: for:maintainability

#238 Make sure apt-get update run at least once
  scripts/system.sh
Labels: for:usability

#239 Simplify and fix post create command
  .devcontainer/devcontainer.json
  scripts/setup.sh
  scripts/system.sh
Labels: for:usability

#240 Add codespace setup to the book
  README.md
  book/src/SUMMARY.md
  book/src/applet/README.md
  book/src/applet/setup.md
  book/src/quick/README.md
Labels: for:usability

#241 Mention how to run without USB in the book
  book/src/applet/run.md
Labels: for:usability

#242 Assume --no-default-features in codespace
  book/src/applet/run.md
  book/src/quick/README.md
  crates/xtask/src/main.rs
Labels: for:usability

#243 Compile xtask after codespace creation
  .devcontainer/devcontainer.json
Labels: for:usability

#245 Automatically deploy the book
  .github/workflows/ci.yml
  .github/workflows/pages.yml
  scripts/pages.sh
Labels: for:maintainability

#246 Migrate to probe-rs now that probe-run is deprecated
  .github/workflows/ci.yml
  book/src/applet/run.md
  crates/xtask/src/main.rs
  scripts/wrapper.sh
Labels: crate:xtask, for:maintainability

#247 Fix deploy pages workflow
  .github/workflows/pages.yml
  scripts/pages.sh
Labels: for:maintainability

#248 Use div_ceil from the standard library
  crates/store/CHANGELOG.md
  crates/store/src/format.rs
Labels: for:maintainability

#250 Update CITATION.cff
  CITATION.cff
Labels: for:usability

#251 Improve filesystem functions and error messages
  crates/xtask/src/fs.rs
  crates/xtask/src/main.rs
Labels: for:maintainability

#258 Permit board implementation to customize debug print
  crates/board/CHANGELOG.md
  crates/board/src/debug.rs
  crates/scheduler/CHANGELOG.md
  crates/scheduler/src/call/debug.rs
Labels: crate:board, for:usability

#259 Make sure all source files have a copyright notice
  .github/workflows/ci.yml
  scripts/ci-copyright.sh
  scripts/ci.sh
  scripts/publish.sh
  scripts/upgrade.sh
Labels: for:maintainability

#262 Fix usbip package in ubuntu
  scripts/system.sh
Labels: for:usability

#265 Make Serial::register() unsafe
  crates/prelude/CHANGELOG.md
  crates/prelude/src/serial.rs
  crates/prelude/src/uart.rs
  crates/prelude/src/usb/serial.rs
Labels: lang:rust, for:security

#269 Only run the applet when the web UI is ready
  crates/runner-host/crates/web-common/src/lib.rs
  crates/runner-host/crates/web-server/src/lib.rs
Labels: for:usability, runner:host

#267 Make the web UI a PWA
  .devcontainer/devcontainer.json
  crates/runner-host/crates/web-server/public/board.js
  crates/runner-host/crates/web-server/public/favicon.png
  crates/runner-host/crates/web-server/public/index.html
  crates/runner-host/crates/web-server/public/manifest.json
  crates/runner-host/crates/web-server/public/service-worker.js
  scripts/ci-copyright.sh
Labels: for:usability, runner:host

#272 Prevent applets to call into unsupported operations
  crates/board/CHANGELOG.md
  crates/board/src/crypto.rs
  crates/board/src/crypto/ecc.rs
  crates/scheduler/CHANGELOG.md
  crates/scheduler/src/call/crypto/ccm.rs
  crates/scheduler/src/call/crypto/ec.rs
  crates/scheduler/src/call/crypto/gcm.rs
  crates/scheduler/src/call/crypto/hash.rs
  crates/scheduler/src/lib.rs
Labels: crate:board, for:security, crate:scheduler

#273 Add tips for github codespace
  .devcontainer/devcontainer.json
  book/src/SUMMARY.md
  book/src/quick/README.md
  book/src/quick/codespace.md
Labels: for:usability

#274 Make serial::Serial sealed
  crates/prelude/CHANGELOG.md
  crates/prelude/src/serial.rs
  crates/prelude/src/uart.rs
  crates/prelude/src/usb/serial.rs
Labels: lang:rust, for:usability, for:maintainability

#275 Assume bash for the publish script for simplicity
  scripts/publish.sh
Labels: for:maintainability
