Repository google/wasefire, pull requests merged in 2024-04, with the labels that each got.

#427 Bump h2 from 0.3.24 to 0.3.26
  crates/runner-host/Cargo.lock
  crates/runner-host/crates/web-server/Cargo.lock
Labels: for:maintainability

#430 Disable fail-fast for checks
  .github/workflows/ci.yml
Labels: for:maintainability

#431 Ensure board API is documented
  crates/board/CHANGELOG.md
  crates/board/Cargo.lock
  crates/board/Cargo.toml
  crates/board/src/crypto.rs
  crates/board/src/crypto/aead.rs
  crates/board/src/crypto/ecc.rs
  crates/board/src/gpio.rs
  crates/board/src/lib.rs
  crates/board/src/platform.rs
  crates/board/src/radio.rs
  crates/board/src/timer.rs
  crates/board/src/usb.rs
  crates/board/src/usb/serial.rs
  crates/runner-host/Cargo.lock
  crates/runner-nordic/Cargo.lock
  crates/scheduler/CHANGELOG.md
  crates/scheduler/Cargo.lock
  crates/scheduler/Cargo.toml
Labels: crate:board, for:usability, for:maintainability

#432 Update todo for bytemuck release
  crates/board/CHANGELOG.md
  crates/board/src/gpio.rs
Labels: crate:board, for:maintainability

#433 Ensure Rust prelude is documented
  crates/prelude/CHANGELOG.md
  crates/prelude/Cargo.toml
  crates/prelude/src/crypto/ec.rs
  crates/prelude/src/crypto/gcm.rs
  crates/prelude/src/debug.rs
  crates/prelude/src/lib.rs
  crates/prelude/src/radio/ble.rs
Labels: lang:rust, for:usability, for:maintainability

#434 `led::{get, set}`: panic with an `InvalidArgument` error instead of trapping
  crates/prelude/CHANGELOG.md
  crates/prelude/src/led.rs
  crates/scheduler/CHANGELOG.md
  crates/scheduler/src/call/led.rs
Labels: lang:rust, for:usability, crate:scheduler

#436 Add a textreview check
  .gitattributes
  .github/actions/ci-checks/action.yml
  .github/workflows/ci.yml
  book/src/applet/run.md
  crates/board/CHANGELOG.md
  crates/board/Cargo.lock
  crates/board/Cargo.toml
  crates/runner-host/Cargo.lock
  crates/runner-nordic/Cargo.lock
  crates/scheduler/CHANGELOG.md
  crates/scheduler/Cargo.lock
  crates/scheduler/Cargo.toml
  crates/store/CHANGELOG.md
  crates/store/Cargo.lock
  crates/store/Cargo.toml
  crates/store/fuzz/Cargo.lock
  crates/store/src/format.rs
  crates/store/src/lib.rs
  crates/store/src/store.rs
  crates/xtask/src/main.rs
  crates/xtask/src/textreview.rs
  scripts/ci-copyright.sh
  scripts/ci.sh
  scripts/log.sh
Labels: crate:xtask, for:maintainability

#443 Remove work-around microsoft-prod missing signature
  .github/actions/ci-checks/action.yml
  .github/workflows/pages.yml
Labels: for:maintainability

#447 Add documentation about changelogs
  CONTRIBUTING.md
  docs/contributing/changelog.md
Labels: for:maintainability
