Repository google/wasefire, pull requests merged in 2024-02, with the labels that each got.

#393 Add gpio::last_write() for stateful output GPIOs
  crates/api-desc/CHANGELOG.md
  crates/api-desc/src/gpio.rs
  crates/board/CHANGELOG.md
  crates/board/src/gpio.rs
  crates/prelude/CHANGELOG.md
  crates/prelude/src/gpio.rs
  crates/runner-nordic/src/board/gpio.rs
  crates/scheduler/CHANGELOG.md
  crates/scheduler/src/call/gpio.rs
  examples/assemblyscript/api.ts
Labels: lang:rust, crate:board, for:usability, crate:scheduler, crate:api, runner:nordic

#394 Update taplo-cli to get rid of special treatment
  .github/actions/ci-cache/action.yml
  scripts/wrapper.sh
Labels: for:maintainability

#395 Make gcm::Key deref to aead::Key
  crates/prelude/CHANGELOG.md
  crates/prelude/src/crypto/gcm.rs
Labels: lang:rust, for:usability

#396 Use spin crate for mutex implementation
  crates/prelude/Cargo.lock
  crates/runner-host/Cargo.lock
  crates/runner-nordic/Cargo.lock
  crates/scheduler/Cargo.lock
  crates/sync/CHANGELOG.md
  crates/sync/Cargo.lock
  crates/sync/Cargo.toml
  crates/sync/src/mutex.rs
  examples/rust/blink/Cargo.lock
  examples/rust/blink_periodic/Cargo.lock
  examples/rust/button/Cargo.lock
  examples/rust/button_abort/Cargo.lock
  examples/rust/ccm/Cargo.lock
  examples/rust/ctap/Cargo.lock
  examples/rust/ec_test/Cargo.lock
  examples/rust/echo/Cargo.lock
  examples/rust/exercises/client/Cargo.lock
  examples/rust/exercises/interface/Cargo.lock
  examples/rust/exercises/part-1-sol/Cargo.lock
  examples/rust/exercises/part-1/Cargo.lock
  examples/rust/exercises/part-2-sol/Cargo.lock
  examples/rust/exercises/part-2/Cargo.lock
  examples/rust/exercises/part-3-sol/Cargo.lock
  examples/rust/exercises/part-3/Cargo.lock
  examples/rust/exercises/part-4-sol/Cargo.lock
  examples/rust/exercises/part-4/Cargo.lock
  examples/rust/exercises/part-5-sol/Cargo.lock
  examples/rust/exercises/part-5/Cargo.lock
  examples/rust/exercises/part-6-sol/Cargo.lock
  examples/rust/exercises/part-6/Cargo.lock
  examples/rust/exercises/part-7-sol/Cargo.lock
  examples/rust/exercises/part-7/Cargo.lock
  examples/rust/gcm_test/Cargo.lock
  examples/rust/gpio_test/Cargo.lock
  examples/rust/hash_test/Cargo.lock
  examples/rust/hello/Cargo.lock
  examples/rust/hsm/Cargo.lock
  examples/rust/hsm/common/Cargo.lock
  examples/rust/led/Cargo.lock
  examples/rust/link_test/Cargo.lock
  examples/rust/memory_game/Cargo.lock
  examples/rust/oom/Cargo.lock
  examples/rust/panic/Cargo.lock
  examples/rust/perf/Cargo.lock
  examples/rust/rand/Cargo.lock
  examples/rust/reboot/Cargo.lock
  examples/rust/rng_test/Cargo.lock
  examples/rust/store/Cargo.lock
  examples/rust/store_test/Cargo.lock
  examples/rust/sync_test/Cargo.lock
  examples/rust/syscall_test/Cargo.lock
  examples/rust/timer/Cargo.lock
  examples/rust/timer_test/Cargo.lock
  examples/rust/update/Cargo.lock
  examples/rust/version/Cargo.lock
Labels: for:maintainability

#397 Add --probe-rs flag to xtask runner
  crates/xtask/src/main.rs
Labels: crate:xtask, for:usability

#398 Clarify conditions when serial events trigger
  crates/api-desc/CHANGELOG.md
  crates/api-desc/src/uart.rs
  crates/api-desc/src/usb/serial.rs
  crates/board/CHANGELOG.md
  crates/board/src/uart.rs
  crates/board/src/usb/serial.rs
  examples/assemblyscript/api.ts
Labels: crate:board, for:usability, crate:api

#400 Add an example applet for a bridge between UART and USB serial
  examples/rust/uart-usb/Cargo.lock
  examples/rust/uart-usb/Cargo.toml
  examples/rust/uart-usb/src/lib.rs
Labels: for:maintainability

#402 Add error and sync to the publish script
  scripts/publish.sh
Labels: for:maintainability

#404 Generate release changelog
  docs/releases/2024-02-27.md
  scripts/announce.sh
Labels: for:maintainability

#405 Add --web-host and --web-port flags to xtask and host runner
  crates/runner-host/Cargo.lock
  crates/runner-host/Cargo.toml
  crates/runner-host/src/main.rs
  crates/xtask/src/main.rs
Labels: crate:xtask, for:usability, runner:host
